export const SERVICES = [
  {
    name: 'Metal Buildings',
    slug: 'metal-buildings',
    img: '/images/services/metal-buildings.jpg',
    tagline: 'Durable. Versatile. Built Louisiana-tough.',
    description:
      'B. Edwards Construction is a local leader in resilient metal buildings across Louisiana. These structures offer long-lasting protection against weather and structural wear — cost-effective and adaptable for any application.',
  },
  {
    name: 'Concrete Foundations',
    slug: 'concrete-foundations',
    img: '/images/services/concrete-foundations.jpg',
    tagline: 'Solid ground for everything you build.',
    description:
      'Our foundations resist environmental elements and minimize long-term maintenance. High-quality materials combined with expert craftsmanship create a stable base that stands the test of time.',
  },
  {
    name: 'Roofs',
    slug: 'roofs',
    img: '/images/services/roofs.jpg',
    tagline: 'Protection from the top down.',
    description:
      'A well-constructed roof safeguards your property against unpredictable elements while contributing to energy efficiency and long-term value. We build roofs that last.',
  },
  {
    name: 'Shops',
    slug: 'shops',
    img: '/images/services/shops.jpg',
    tagline: 'Your workspace, built right.',
    description:
      'Quality shop construction provides a secure, functional, and durable workspace. Reduced maintenance costs and enhanced energy efficiency make it a smart long-term investment for any trade.',
  },
  {
    name: 'Camps',
    slug: 'camps',
    img: '/images/services/camps.jpg',
    tagline: 'Built for comfort and durability.',
    description:
      'We build safe, resilient camp structures tailored to your needs. Quality construction ensures comfort, security, and longevity — whether for hunting, recreation, or extended stays.',
  },
  {
    name: 'Barns',
    slug: 'barns',
    img: '/images/services/barns.jpg',
    tagline: 'From site prep to final nail.',
    description:
      'Our builders meet industry standards for structural integrity and longevity — creating reliable, efficient spaces for agricultural and storage needs. From site preparation to assembly, we deliver.',
  },
  {
    name: 'Patios',
    slug: 'patios',
    img: '/images/services/patios.jpg',
    tagline: 'Outdoor living done properly.',
    description:
      'A well-constructed patio enhances curb appeal and structural stability. We address drainage issues, soil conditions, and design to give you a reliable, beautiful outdoor space.',
  },
];

export const GALLERY: string[] = [
  '/images/gallery/gallery-26.jpg',
  '/images/gallery/gallery-05.jpg',
  '/images/gallery/gallery-08.jpg',
  '/images/gallery/gallery-29.jpg',
  '/images/gallery/gallery-14.jpg',
  '/images/gallery/gallery-01.jpg',
  '/images/gallery/gallery-02.jpg',
  '/images/gallery/gallery-03.jpg',
  '/images/gallery/gallery-04.jpg',
  '/images/gallery/gallery-06.jpg',
  '/images/gallery/gallery-07.jpg',
  '/images/gallery/gallery-09.jpg',
  '/images/gallery/gallery-10.jpg',
  '/images/gallery/gallery-11.jpg',
  '/images/gallery/gallery-12.jpg',
  '/images/gallery/gallery-13.jpg',
  '/images/gallery/gallery-15.jpg',
  '/images/gallery/gallery-16.jpg',
  '/images/gallery/gallery-17.jpg',
  '/images/gallery/gallery-18.jpg',
  '/images/gallery/gallery-19.jpg',
  '/images/gallery/gallery-20.jpg',
  '/images/gallery/gallery-21.jpg',
  '/images/gallery/gallery-22.jpg',
  '/images/gallery/gallery-23.jpg',
  '/images/gallery/gallery-24.jpg',
  '/images/gallery/gallery-25.jpg',
  '/images/gallery/gallery-27.jpg',
  '/images/gallery/gallery-28.jpg',
];

export const HERO_GALLERY = GALLERY.slice(0, 6);

export const BLOG_POSTS = [
  {
    slug: 'what-makes-construction-difficult-in-louisiana',
    tag: 'Industry',
    date: 'April 2025',
    title: 'What Makes Construction So Difficult in Louisiana?',
    excerpt:
      'Between the soil, the storms, and the humidity, Louisiana is one of the toughest places in the country to build. Here\'s what every property owner should know.',
    img: '/images/gallery/gallery-08.jpg',
    body: [
      { type: 'paragraph' as const, content: 'Louisiana is a beautiful place to live, but it\'s one of the hardest states in the country to build in. If you\'ve ever wondered why construction projects here seem to take longer, cost more, or require different techniques than what you see in other states — the answer is under your feet, in the air, and in the forecast.' },
      { type: 'heading' as const, content: 'The Soil Problem' },
      { type: 'paragraph' as const, content: 'Most of Louisiana sits on clay-heavy, expansive soil. That means the ground swells when it\'s wet and shrinks when it dries. This constant movement puts tremendous stress on foundations, slabs, and any structure that sits directly on grade. Builders who don\'t account for soil conditions end up with cracked slabs, shifting walls, and drainage failures within a few years.' },
      { type: 'paragraph' as const, content: 'In many parts of the state — especially near rivers and bayous — the water table is extremely high. Dig down two or three feet and you hit water. That limits foundation options and requires engineered drainage solutions from day one. It\'s not something you can fix after the fact.' },
      { type: 'heading' as const, content: 'Hurricanes and Severe Weather' },
      { type: 'paragraph' as const, content: 'Louisiana is in the direct path of Gulf hurricanes. Every building erected in this state needs to meet wind load requirements that would seem extreme in most other parts of the country. Metal buildings, in particular, must be engineered to handle sustained winds of 130+ mph in coastal zones, with proper anchor bolts, bracing, and connection design.' },
      { type: 'paragraph' as const, content: 'Beyond hurricanes, Louisiana gets severe thunderstorms, tornadoes, and flooding. Builders have to think about not just structural integrity but also elevation, water intrusion, and long-term moisture management. It\'s a different engineering mindset than building in, say, Texas or Tennessee.' },
      { type: 'heading' as const, content: 'Heat and Humidity' },
      { type: 'paragraph' as const, content: 'The Louisiana climate is brutally humid eight months of the year. That humidity affects every material on a job site — from steel that rusts faster to wood that expands and warps. Concrete curing times are different here. Paint adhesion is different here. Even the schedule is different — crews can only work safely during certain hours in the summer months without risking heat-related illness.' },
      { type: 'paragraph' as const, content: 'HVAC and ventilation planning become critical at the design phase, not as afterthoughts. A metal building without proper ventilation in Louisiana becomes an oven. A poorly insulated concrete slab sweats. These are problems that experienced Louisiana builders know how to prevent before they happen.' },
      { type: 'heading' as const, content: 'Permits, Codes, and Regulations' },
      { type: 'paragraph' as const, content: 'Louisiana\'s building codes vary significantly by parish. What\'s required in Rapides Parish might be different from Catahoula or Concordia. Flood zone designations, setback requirements, and elevation certificates all add layers of complexity — and cost — that builders in other states simply don\'t deal with.' },
      { type: 'heading' as const, content: 'Why Local Experience Matters' },
      { type: 'paragraph' as const, content: 'This is exactly why hiring a Louisiana-based builder matters. A contractor from out of state may know how to erect a metal building, but they may not know how to anchor it to Louisiana soil, insulate it for Louisiana humidity, or engineer it for Louisiana wind loads. Local experience isn\'t just a nice-to-have — it\'s the difference between a building that lasts and one that doesn\'t.' },
      { type: 'paragraph' as const, content: 'At B. Edwards Construction, we\'ve built across central Louisiana for years. We understand the soil, the weather, the code requirements, and the unique challenges that come with every project in this state. If you\'re planning a build, talk to someone who knows what they\'re up against.' },
    ],
  },
  {
    slug: 'construction-trends-louisiana-2025',
    tag: 'Trends',
    date: 'March 2025',
    title: 'Construction Trends in Louisiana Right Now',
    excerpt:
      'From pre-engineered metal buildings to rural land development, here\'s what\'s driving construction across the state in 2025.',
    img: '/images/gallery/gallery-26.jpg',
    body: [
      { type: 'paragraph' as const, content: 'The construction industry in Louisiana is shifting. Material costs, workforce availability, and changing property owner expectations are all reshaping what gets built, how fast, and at what price point. Whether you\'re a landowner, farmer, or business owner, these trends directly affect your next project.' },
      { type: 'heading' as const, content: 'Metal Buildings Are Dominating' },
      { type: 'paragraph' as const, content: 'Pre-engineered metal buildings have become the default for shops, barns, storage, and even residences in rural Louisiana. The reasons are simple: they go up faster, cost less per square foot, require less maintenance, and handle Louisiana\'s wind and storm conditions better than most wood-frame alternatives.' },
      { type: 'paragraph' as const, content: 'We\'re seeing more and more property owners choose metal for their primary structures — not just outbuildings. The stigma of "metal barn" is gone. Modern metal buildings with insulation, finished interiors, and quality concrete slabs are functionally equivalent to traditional construction at a fraction of the timeline.' },
      { type: 'heading' as const, content: 'Rural Land Development' },
      { type: 'paragraph' as const, content: 'With property prices in metro areas continuing to climb, there\'s a strong trend toward developing rural land — especially in central Louisiana. Landowners are building shops, camps, and residential structures on family land that\'s been sitting undeveloped for decades. This creates demand for full-service builders who can handle everything from site clearing and grading to foundation, structure, and finish.' },
      { type: 'heading' as const, content: 'Concrete Quality Is Getting More Attention' },
      { type: 'paragraph' as const, content: 'Foundation failures have been a major pain point in Louisiana for years. As a result, property owners are paying more attention to concrete quality, mix design, and reinforcement than ever before. The era of "just pour a slab" is over. Owners want engineered foundations, proper rebar schedules, and moisture barriers — and they\'re willing to pay for them.' },
      { type: 'heading' as const, content: 'Workforce Challenges' },
      { type: 'paragraph' as const, content: 'Skilled labor remains the biggest bottleneck in Louisiana construction. Experienced welders, concrete finishers, and metal erectors are in high demand and short supply. This puts a premium on established crews — companies that have retained their people and can deliver consistent quality without subcontracting every phase of the job.' },
      { type: 'heading' as const, content: 'Energy Efficiency and Insulation' },
      { type: 'paragraph' as const, content: 'Rising energy costs are pushing property owners to invest in better insulation, reflective roofing materials, and proper ventilation from the start. A well-insulated metal building with ridge vents and proper vapor barriers costs slightly more upfront but saves thousands in cooling costs over its lifetime. Smart builders are designing for this from day one.' },
      { type: 'paragraph' as const, content: 'The bottom line: Louisiana construction in 2025 is about building smarter, not just building. The builders who understand these trends — and can execute on them — are the ones worth hiring.' },
    ],
  },
  {
    slug: 'good-vs-great-construction-company',
    tag: 'Advice',
    date: 'February 2025',
    title: 'How to Tell the Difference Between a Good Construction Company and a Great One',
    excerpt:
      'Anyone can pour concrete and bolt steel. Here\'s how to identify the contractors who actually care about the work — and the ones who are just collecting checks.',
    img: '/images/gallery/gallery-01.jpg',
    body: [
      { type: 'paragraph' as const, content: 'Louisiana has no shortage of construction companies. A quick search will give you dozens of options within driving distance. But choosing the wrong one can cost you tens of thousands of dollars, months of delays, and a structure that doesn\'t hold up. Here\'s how to separate the good from the great.' },
      { type: 'heading' as const, content: 'They Show You Their Work — Not Stock Photos' },
      { type: 'paragraph' as const, content: 'A great construction company has a portfolio of real projects. Not renders, not stock images — actual buildings they\'ve built, photographed on site. Ask to see completed projects. Ask for addresses you can drive by. If a contractor can\'t show you what they\'ve built, that tells you everything you need to know.' },
      { type: 'heading' as const, content: 'They Talk About What Can Go Wrong' },
      { type: 'paragraph' as const, content: 'Good contractors tell you what you want to hear. Great contractors tell you what you need to hear. If a builder never mentions soil testing, drainage, wind load engineering, or permit requirements — they\'re either cutting corners or they don\'t know enough to bring it up. Both are red flags.' },
      { type: 'paragraph' as const, content: 'The best contractors will walk your site and immediately start identifying potential problems: grading issues, access limitations, utility setbacks, soil concerns. They do this because they\'ve been burned before and they don\'t want either of you to deal with preventable problems.' },
      { type: 'heading' as const, content: 'Their Crew Is Their Crew' },
      { type: 'paragraph' as const, content: 'A lot of contractors are essentially project managers who subcontract every trade. That\'s not inherently bad, but it introduces variables — different crews, different quality standards, different accountability. Great construction companies have their own core team. The people who pour your foundation are the same people who\'ve been doing it for that company for years. Consistency matters.' },
      { type: 'heading' as const, content: 'They Give You a Real Timeline — Not a Fantasy' },
      { type: 'paragraph' as const, content: 'If someone quotes you a timeline that sounds too good to be true, it is. Great contractors build weather delays, material lead times, and inspection schedules into their estimates. They\'d rather tell you six weeks and deliver in five than tell you three weeks and deliver in eight.' },
      { type: 'heading' as const, content: 'They Don\'t Disappear After the Check Clears' },
      { type: 'paragraph' as const, content: 'The mark of a great company is what happens after the job is done. Do they answer the phone six months later when you have a question? Do they come back to address a minor issue without a fight? The companies that stick around are the ones that have built their reputation on relationships, not just transactions.' },
      { type: 'heading' as const, content: 'The Bottom Line' },
      { type: 'paragraph' as const, content: 'Price is important, but it\'s never the only factor. The cheapest bid often becomes the most expensive project. Look for experience, transparency, real work history, and a team that treats your project like their reputation depends on it — because it does.' },
    ],
  },
  {
    slug: 'why-metal-buildings-smart-choice-louisiana',
    tag: 'Metal Buildings',
    date: 'January 2025',
    title: 'Why Metal Buildings Are the Smart Choice in Louisiana',
    excerpt:
      'From humidity to hurricanes, Louisiana\'s climate demands structures built to last. Here\'s why metal is the material of choice for smart builders across the state.',
    img: '/images/gallery/gallery-05.jpg',
    body: [
      { type: 'paragraph' as const, content: 'If you\'re building in Louisiana, you need a structure that can handle what this state throws at it. That means wind, water, heat, humidity, and soil that never stays still. For decades, metal buildings have proven themselves as the most practical, durable, and cost-effective option for Louisiana property owners — and there are real reasons why.' },
      { type: 'heading' as const, content: 'Wind and Storm Resistance' },
      { type: 'paragraph' as const, content: 'Pre-engineered metal buildings are designed to meet specific wind load requirements. In Louisiana, that often means engineering for 130+ mph winds in hurricane zones. Unlike wood-frame structures that rely on hundreds of individual connections, metal buildings use rigid frames, moment-resistant connections, and continuous purlins that distribute force across the entire structure. They flex without breaking.' },
      { type: 'paragraph' as const, content: 'After every major hurricane, the buildings left standing in rural Louisiana are overwhelmingly metal. That\'s not a coincidence — it\'s engineering.' },
      { type: 'heading' as const, content: 'Moisture and Humidity' },
      { type: 'paragraph' as const, content: 'Wood rots. Steel doesn\'t. In a state where humidity levels regularly exceed 90%, that distinction matters enormously. Modern metal buildings use galvanized or Galvalume-coated steel panels that resist corrosion, and with proper insulation and vapor barriers, they eliminate the condensation problems that plague poorly built structures.' },
      { type: 'heading' as const, content: 'Speed of Construction' },
      { type: 'paragraph' as const, content: 'A typical metal building can be erected in a fraction of the time a comparable wood-frame structure takes. Components arrive pre-cut and pre-drilled from the factory. Framing, sheeting, and trim go up in days, not weeks. For landowners who need functional space quickly — whether for equipment storage, livestock, or a workshop — metal is the fastest path from dirt to done.' },
      { type: 'heading' as const, content: 'Long-Term Cost' },
      { type: 'paragraph' as const, content: 'The upfront cost of a metal building is competitive with wood-frame construction, but the long-term cost is where metal wins decisively. No painting every few years. No termite treatment. No rotting fascia boards. No warped framing. A well-built metal building with a quality foundation will last 40-50 years with minimal maintenance. Try getting that from a stick-built structure in Louisiana.' },
      { type: 'heading' as const, content: 'Versatility' },
      { type: 'paragraph' as const, content: 'Metal buildings aren\'t just for barns anymore. We build shops, camps, equipment shelters, hunting lodges, man caves, and full residential structures using metal. The interior can be finished to any standard — insulated walls, climate control, plumbing, electrical, drywall. From the outside it looks like a metal building. From the inside it can look like anything you want.' },
      { type: 'paragraph' as const, content: 'If you\'re planning a build in Louisiana, metal deserves serious consideration. It\'s not the only option, but for most applications, it\'s the smartest one.' },
    ],
  },
  {
    slug: 'before-pouring-concrete-foundation',
    tag: 'Foundations',
    date: 'December 2024',
    title: 'What You Need to Know Before Pouring a Concrete Foundation',
    excerpt:
      'Soil conditions matter more than most people think. We break down the key decisions that determine whether your foundation holds up for decades.',
    img: '/images/gallery/gallery-04.jpg',
    body: [
      { type: 'paragraph' as const, content: 'A foundation is the single most important part of any structure. Get it right, and your building will be solid for decades. Get it wrong, and every other part of the project suffers. Before a single yard of concrete is poured, there are critical decisions that need to be made — and most of them happen before anyone picks up a shovel.' },
      { type: 'heading' as const, content: 'Know Your Soil' },
      { type: 'paragraph' as const, content: 'In Louisiana, soil is the variable that determines everything. Most of the state sits on expansive clay that swells when wet and contracts when dry. If your foundation design doesn\'t account for this movement, you\'ll see cracks within a year or two. Soil testing isn\'t optional — it\'s essential. A basic geotechnical report will tell you the bearing capacity of your soil, the depth to stable material, and whether you need pilings, grade beams, or a standard monolithic slab.' },
      { type: 'heading' as const, content: 'Drainage Comes First' },
      { type: 'paragraph' as const, content: 'Water is the enemy of every foundation. Before pouring, the site needs to be graded so water flows away from the structure in all directions. French drains, swales, or retention areas may be needed depending on the topography. If you skip this step, standing water against your slab will eventually undermine it — no matter how well the concrete was mixed or poured.' },
      { type: 'heading' as const, content: 'Thickness, Rebar, and Reinforcement' },
      { type: 'paragraph' as const, content: 'A standard residential slab in Louisiana is typically 4 inches thick with fiber mesh or wire mesh reinforcement. But for shops, metal buildings, and heavy equipment use, you need thicker slabs — 5 to 6 inches — with a proper rebar grid. The rebar schedule matters: #4 rebar on 12-inch centers is common for structural slabs. Skipping reinforcement saves a few hundred dollars on pour day and costs thousands in repairs later.' },
      { type: 'heading' as const, content: 'Moisture Barriers' },
      { type: 'paragraph' as const, content: 'With Louisiana\'s high water table, vapor barriers under the slab are critical. A 10-mil poly barrier between the compacted fill and the concrete prevents ground moisture from wicking up through the slab. Without it, you get sweating floors, mold problems, and degraded concrete over time. It\'s a $200 investment that prevents $10,000 problems.' },
      { type: 'heading' as const, content: 'Curing Time' },
      { type: 'paragraph' as const, content: 'Concrete doesn\'t dry — it cures through a chemical reaction. In Louisiana\'s heat and humidity, curing conditions are unique. Concrete poured in July needs to be kept moist and may need curing compound applied to prevent surface cracking from rapid moisture loss. Pouring and walking away is the fastest path to a failed slab. Proper curing takes 7 days minimum, with 28 days to reach full strength.' },
      { type: 'paragraph' as const, content: 'The foundation is where your project starts, and it\'s where most shortcuts are taken. Don\'t let it be. A properly planned and poured foundation is the best investment you can make in any build.' },
    ],
  },
  {
    slug: 'planning-shop-or-barn-build',
    tag: 'Barns & Shops',
    date: 'November 2024',
    title: 'Building a Shop or Barn: What to Plan for Before You Start',
    excerpt:
      'Site preparation, permits, utilities — the decisions you make before the first post goes in the ground are the ones that define the final result.',
    img: '/images/gallery/gallery-09.jpg',
    body: [
      { type: 'paragraph' as const, content: 'Building a shop or barn sounds simple enough — pick a spot, pour a slab, put up a building. But the projects that go smoothly are the ones where the planning happened before the building started. Every decision you make in the first two weeks affects the next twenty years of that structure\'s life.' },
      { type: 'heading' as const, content: 'Site Selection' },
      { type: 'paragraph' as const, content: 'Where you place your building on the property matters more than most people realize. You need to consider access — can a concrete truck, delivery trailer, and crane reach the location? You need to think about drainage — is the pad area at the low point of the property where water collects? You need to check setback requirements for your parish. And you need to think about future use — will you want to expand, add a lean-to, or connect utilities later?' },
      { type: 'heading' as const, content: 'Sizing It Right' },
      { type: 'paragraph' as const, content: 'The most common regret among shop and barn owners: "I wish I\'d built it bigger." If you\'re thinking about a 30x40, build a 40x60. If you\'re thinking 40x60, seriously consider 50x80. The foundation and the building cost more, but the cost per square foot drops significantly as you scale up. And once the concrete is poured, you can\'t make it bigger without starting over.' },
      { type: 'heading' as const, content: 'Utilities and Electrical' },
      { type: 'paragraph' as const, content: 'Plan your electrical before the slab is poured, not after. If you want floor outlets, conduit runs, or in-ground electrical, that work has to happen before concrete. Same with plumbing — if there\'s any chance you\'ll want a bathroom, wash bay, or drain in the future, run the rough plumbing now. Cutting into a cured slab to add plumbing later is expensive and messy.' },
      { type: 'heading' as const, content: 'Doors and Openings' },
      { type: 'paragraph' as const, content: 'Think about what\'s going in and out of this building. If you\'re storing a tractor, the door needs to be tall and wide enough to clear it with room to spare. Overhead doors typically come in standard sizes — 10x10, 12x12, 14x14 — and the framed opening has to be designed for the specific door. Getting this wrong means reframing or living with a door that doesn\'t fit your equipment.' },
      { type: 'heading' as const, content: 'Insulation and Ventilation' },
      { type: 'paragraph' as const, content: 'If you\'re going to spend any time working in the building, insulate it. A non-insulated metal building in Louisiana summer is 140°F inside. With proper insulation and ventilation — ridge vents, exhaust fans, or a mini-split system — it becomes a comfortable, functional workspace. The cost to insulate during construction is a fraction of what it costs to retrofit later.' },
      { type: 'heading' as const, content: 'The Lesson' },
      { type: 'paragraph' as const, content: 'Build once. Build right. The decisions that feel small during planning — site grade, slab thickness, door size, insulation — are the ones that determine whether your shop or barn serves you well for the next 30 years or becomes a source of constant frustration. Take the time to plan it properly, and the build itself becomes the easy part.' },
    ],
  },
];

export const BUSINESS = {
  name: 'B. Edwards Construction',
  phone: '(318) 481-7588',
  phoneHref: 'tel:3184817588',
  address: '350 Red Oak Tree Dr., Jonesville, LA',
  googleMapsUrl:
    'https://www.google.com/maps/place/B+Edwards+Construction/@31.5086091,-91.7334082,795m/data=!3m2!1e3!4b1!4m6!3m5!1s0x862f7ff315a7f4c9:0x60a3cc8d0ac89947!8m2!3d31.5086091!4d-91.7334082!16s%2Fg%2F11vj542s0h',
  googleReviewUrl:
    'https://www.google.com/maps/place/B+Edwards+Construction/@31.5086091,-91.7334082,795m/data=!3m2!1e3!4b1!4m6!3m5!1s0x862f7ff315a7f4c9:0x60a3cc8d0ac89947!8m2!3d31.5086091!4d-91.7334082!16s%2Fg%2F11vj542s0h?entry=ttu',
  email: 'info@bedwardsconstruction.com',
};
